// c06_bridge.js: the noir bridge (87.74-104.63). Paper, ink and red only; night blue floods in at the very end.
// Half-time: long shots, slow pushes, stepped acting. The one moment in the film where someone reads carefully.
(() => {
  const P = INK.paper, K = INK.ink, R = INK.red, RD = INK.redDk, WH = INK.white;
  const G1 = mix(K, P, .2), G2 = mix(K, P, .4), G3 = mix(K, P, .62);          // ink screens (tints), never hues
  const NOIR = { hoodie: G1, hoodieDk: K, hoodieLt: G2, fur: WH, furDk: G3, ear: G3, nose: G2, line: K, pen: R, cheek: G3 };
  const BAGS = .6;
  const EVIL = "Robert'); DROP TABLE users;--";
  const Q = [['const q = "SELECT * FROM users WHERE name = \'" + ', null], ['req.query.name', 'red'], [' + "\'";', null]];
  const QS = Q.map(s => s[0]).join('');
  const W12 = { now: 89.60, there: 92.86, flag: 94.64, red: 95.18, caps: 95.84, paw: 96.68, merge: 98.56, shipped: 99.88, flaw: 101.06, end: 104.63 };
  const fr = t => Math.floor(t * 24 + 1e-6);
  const cutAt = s => Math.floor(s * 24) / 24 - 1e-4;                          // the frame that contains the sound

  // ---------- the code (lines around 9012) ----------
  const BITS = ['const result = await fix(input);', 'if (x !== undefined && x !== null) {', 'return a ? b ? c : d : e;', 'console.log("here");',
    '// TODO: remove before merge', 'export function fix(data) {', 'const user = users.find(u => u.id === id);', 'items.map(i => i.value).filter(Boolean);',
    '});', 'await sleep(1000); // fixes race', 'let tmp2 = structuredClone(tmp);', 'try { return JSON.parse(s) } catch {}', 'if (!user) return user.name;',
    'const retries = 99;', '// generated by agent', '}', 'res.status(200).json({ ok: true });', 'const token = req.headers.auth;', 'db.close(); // maybe'];
  const NAMED = { 9008: "app.get('/users', async (req, res) => {", 9009: '  // TODO: validate input (later)', 9010: '  const db = await pool.connect();',
    9011: '  console.log("here");', 9013: '  const rows = await db.query(q);', 9014: '  res.json(rows);', 9015: '});' };
  const code = n => n === 9012 ? '  ' + QS : NAMED[n] ?? '  '.repeat(Math.floor(hash(n * 1.7) * 3)) + BITS[Math.floor(hash(n * 3.3) * BITS.length)];
  // segments [[text, color|null]] of line n (9012 carries the red taint)
  const segs = n => n === 9012 ? [['  ' + Q[0][0], null], [Q[1][0], 'red'], [Q[2][0], null]] : [[code(n), null]];

  // ---------- pinhole camera for the 3D sets (y down, floor at Y = 0, up is -Y) ----------
  // C = {x, y, z, f, cx, cy, yaw (+ looks left)}
  const pj = (C, X, Y, Z) => {
    const c = Math.cos(C.yaw || 0), s = Math.sin(C.yaw || 0), dx = X - C.x, dz = Z - C.z;
    const x = dx * c + dz * s, z = Math.max(.5, -dx * s + dz * c);
    return [C.cx + C.f * x / z, C.cy + C.f * (Y - C.y) / z, z];
  };

  // ---------- noir rabbit ----------
  const noirPose = o => ({ bags: BAGS, noShadow: true, ...o, col: { ...NOIR, ...(o.col || {}) } });
  // Replicates the rig's head matrix so private overlays (hood, eye reflections) sit exactly on the head.
  function headM(x, y, s, o) {
    const sq = o.sq || 0, sx = (1 + sq * .22) * (o.flip ? -1 : 1), sy = 1 - sq * .22, turn = clamp(o.turn || 0, -1, 1);
    return new DOMMatrix().translate(x, y).scale(s * sx, s * sy).translate(0, -(o.hop || 0) - 1.9 + (o.sit || 0) * 1.2).rotate(o.lean || 0).translate(0, 1.9)
      .translate(0, -5.45).rotate((o.tilt || 0) + (o.lean || 0) * .3).translate(turn * .1, -2.15 + (o.nod || 0));
  }
  // The rabbit with its hood up like a trench coat: cowl over the head, ears through slits, hatched shadow on the brow.
  function noirRabbit(ctx, x, y, s, o = {}) {
    const pose = noirPose(o), A = rabbit(ctx, x, y, s, pose);
    if (o.hood === false) return A;
    const base = ctx.getTransform(), px = 1 / s, U0 = UPX; ctx.save(); ctx.setTransform(base.multiply(headM(x, y, s, pose))); UPX = px;
    const turn = clamp(pose.turn || 0, -1, 1), tx = turn * .5;
    const outer = [[-2.95 + tx * .3, 2.35], [-3.1, .6], [-2.95, -1.2], [-2.2, -2.45], [-.9, -3.0], [.3 + tx, -3.1], [1.5, -2.85], [2.55, -2.1], [3.05, -.8], [3.05, .9], [2.9, 2.35], [2.2, 2.2], [2.35, .4], [2.05, -1.1], [1.1, -1.95], [0, -2.1], [-1.1, -1.95], [-2.05, -1.1], [-2.35, .4], [-2.2, 2.2]];
    ink(ctx, outer, { fill: G1, hatch: { color: K, spacing: 9 * px, width: 3 * px, angle: -Math.PI / 3, dir: [.6, .8], from: -.2 }, line: 5.2 * px, boil: 1.3 * px, seed: 61 });
    // hood shadow falling on the brow: a hatched band above the eyes (the eyes stay clear)
    ctx.save(); clipPts(ctx, headPts(turn)); hatch(ctx, [[-2.6, -2.3], [2.6, -2.3], [2.6, -1.25], [0, -1.05], [-2.6, -1.25]], { color: K, spacing: 7 * px, width: 3.2 * px, angle: -Math.PI / 4, jit: 2 * px }); ctx.restore();
    inkLine(ctx, [[-2.05, -1.1], [-1.1, -1.95], [0, -2.1], [1.1, -1.95], [2.05, -1.1]], 5 * px, K, { taper: [.1, .1] });
    // ears through slits in the hood (redrawn on top), then the slit hems
    const E = [earPts(-1, pose.earL, turn), earPts(1, pose.earR, turn)], far = turn > 0 ? 1 : 0;
    drawEar(ctx, E[far], pose, px, true); drawEar(ctx, E[1 - far], pose, px, false);
    for (const e of E) { const b = e.spine[1]; inkLine(ctx, [[b[0] - .65, b[1] + .2], [b[0], b[1] + .42], [b[0] + .65, b[1] + .2]], 4.5 * px, K, { taper: [.2, .2] }); }
    UPX = U0; ctx.restore();
    return A;
  }

  // Back view: the hooded rabbit walking away (the rig only faces the camera). Unit space like the rig; (x, y) = ground point.
  function bunnyBack(ctx, x, y, s, o = {}) {
    const px = 1 / s, U0 = UPX, lift = o.lift || [0, 0], bob = o.bob || 0, look = o.look || 0, sway = o.sway || 0;
    ctx.save(); ctx.translate(x, y); ctx.scale(s, s); UPX = px;
    const L = (pts, w, c = K, tp = [.2, .2]) => inkLine(ctx, pts, w * px, c, { taper: tp });
    // feet: the stepping foot lifts and shrinks (moving away)
    for (const sd of [-1, 1]) { const l = lift[sd < 0 ? 0 : 1], fx = sd * (.95 - l * .15), fy = -.25 - l * .9, k = 1 - l * .18;
      ink(ctx, tube([[sd * .8, -1.8 - bob], [lerp(sd * .8, fx, .5), lerp(-1.8 - bob, fy, .5)], [fx, fy]], () => .9, 6), { fill: WH, shade: { color: G3, spacing: 9 * px, dir: [0, 1], from: -.2, to: .6 }, line: 3.6 * px, boil: 1 * px, seed: sd });
      ink(ctx, ell(fx, fy, .95 * k, .5 * k, 16), { fill: WH, shade: { color: G3, spacing: 9 * px, dir: [0, 1], from: 0, to: .5 }, line: 4 * px, boil: 1 * px, seed: sd * 3 }); }
    ctx.translate(0, -bob);
    const hem = sway * .35;
    const coat = [[-1.75, -5.55], [-2.12, -4.6], [-2.2, -3.3], [-2.6 + hem, -1.5], [-1.25 + hem, -1.28], [0 + hem, -1.4], [1.25 + hem, -1.28], [2.6 + hem, -1.5], [2.2, -3.3], [2.12, -4.6], [1.75, -5.55], [0, -5.8]];
    fillPts(ctx, xform(coat, -.2, 0), P);                                              // rim light on the lit side
    ink(ctx, coat, { fill: G1, shade: { color: K, spacing: 11 * px, dir: [.6, .8], from: -.5, to: 2.2, max: .95 }, line: 5 * px, boil: 1.3 * px, seed: 71 });
    fillPts(ctx, rect(-2.2, -3.62, 4.4, .42), K, false); ink(ctx, rrect(-.32, -3.7, .64, .58, .1), { fill: G2, line: 2.6 * px, boil: .5 * px, smooth: false });
    L([[0, -3.1], [hem * .6, -1.42]], 3); L([[-.5, -5.6], [-.8, -3.7]], 2.4, K, [.3, .5]); L([[.5, -5.6], [.8, -3.7]], 2.4, K, [.3, .5]);
    // arms: left hangs, right is raised forward holding the flashlight (forearm hidden)
    ink(ctx, tube([[-1.8, -5.1], [-2.15, -4.0], [-2.35, -2.95]], () => 1.05, 8), { fill: G1, shade: { color: K, spacing: 10 * px, dir: [.6, .8], from: -.2, to: .6 }, line: 4.4 * px, boil: 1 * px, seed: 72 });
    ink(ctx, ell(-2.4, -2.55, .48, .44, 14), { fill: WH, line: 3.4 * px, boil: .8 * px });
    ink(ctx, tube([[1.8, -5.1], [2.45, -4.6], [2.7, -4.05]], () => 1.05, 8), { fill: G1, shade: { color: K, spacing: 10 * px, dir: [.6, .8], from: -.2, to: .6 }, line: 4.4 * px, boil: 1 * px, seed: 73 });
    // hood from behind, ears through it, the red pen tucked at the right ear
    ctx.translate(look * .45, 0);
    const hood = [[-2.3, -5.95], [-2.78, -7.4], [-2.55, -8.95], [-1.65, -9.85], [0, -10.15], [1.65, -9.85], [2.55, -8.95], [2.78, -7.4], [2.3, -5.95], [1.2, -5.55], [0, -5.45], [-1.2, -5.55]];
    if (look < -.3) { const k = clamp((-look - .3) / .5); ink(ctx, [[-2.5, -8.2], [-2.5 - .7 * k, -7.3], [-2.4 - .5 * k, -6.4], [-2.1, -6.3]], { fill: WH, line: 3.4 * px, boil: .8 * px }); for (const j of [0, 1]) L([[-2.7 - .4 * k, -7.0 + j * .3], [-3.4 - .6 * k, -7.2 + j * .5]], 1.8, K, [.1, .7]); }
    fillPts(ctx, xform(hood, -.2, 0), P);
    ink(ctx, hood, { fill: G1, shade: { color: K, spacing: 11 * px, dir: [.6, .8], from: -.8, to: 2.2, max: .95 }, line: 5.2 * px, boil: 1.3 * px, seed: 74 });
    L([[0, -10.05], [.05, -8], [0, -6.1]], 2.6);
    const ear = (sd, a, b) => { const bx = sd * 1.0, by = -9.2, m = [bx + Math.sin(deg(a)) * 2.4, by - Math.cos(deg(a)) * 2.4], tp = [m[0] + Math.sin(deg(a + b)) * 2.5, m[1] - Math.cos(deg(a + b)) * 2.5];
      const sp = [[bx, by + .3], [lerp(bx, m[0], .5), lerp(by, m[1], .5)], m, [lerp(m[0], tp[0], .55), lerp(m[1], tp[1], .55)], tp];
      const e = tube(sp, s2 => 1.15 * Math.pow(Math.sin(Math.PI * (.18 + .8 * s2)), .55) * (1 - .12 * s2) + .05, 16, sd < 0 ? [.74, .07, .45] : null);
      ink(ctx, e, { fill: WH, shade: { color: G3, spacing: 9 * px, dir: [.6, .8], from: -.2, to: 2.2, max: .8 }, line: 4.2 * px, boil: 1.3 * px, seed: sd < 0 ? 75 : 76 });
      L([[bx - .6, by + .25], [bx, by + .5], [bx + .6, by + .25]], 4.2); };
    ear(-1, -12 + (o.earA || 0), -4 + sway * 6); ear(1, 10 + (o.earA || 0), 3 + sway * 6);
    ctx.save(); ctx.translate(1.9, -9.1); ctx.rotate(deg(58)); ink(ctx, rrect(-1.3, -.18, 2.6, .36, .12), { fill: R, line: 3 * px, boil: .5 * px, smooth: false }); ctx.restore();
    UPX = U0; ctx.restore();
    return { lamp: [x + (2.2 + look * .4) * s, y - (4.7 + bob) * s] };
  }

  // ---------- flashlight: a hard white wedge with a halftone edge ----------
  function wedge(A, T, half, R = 4000) {
    const a = Math.atan2(T[1] - A[1], T[0] - A[0]);
    return [A, [A[0] + Math.cos(a - half) * R, A[1] + Math.sin(a - half) * R], [A[0] + Math.cos(a + half) * R, A[1] + Math.sin(a + half) * R]];
  }
  // light(ctx, poly, drawLit): repaint the scene lit inside the wedge, then a halftone falloff band outside its edges
  function light(ctx, A, T, half, drawLit, band = 70) {
    const wp = wedge(A, T, half);
    ctx.save(); clipPts(ctx, wp, false); drawLit(ctx); ctx.restore();
    const a = Math.atan2(T[1] - A[1], T[0] - A[0]), n1 = [Math.cos(a - half - Math.PI / 2), Math.sin(a - half - Math.PI / 2)], n2 = [Math.cos(a + half + Math.PI / 2), Math.sin(a + half + Math.PI / 2)];
    ctx.save(); clipPts(ctx, wedge(A, T, half * 1.9), false);
    dotsIn(ctx, [-30, -30, W + 30, H + 30], { spacing: 22, color: P, angle: .3,
      k: (x, y) => { const d = Math.max((x - A[0]) * n1[0] + (y - A[1]) * n1[1], (x - A[0]) * n2[0] + (y - A[1]) * n2[1]); const r = Math.hypot(x - A[0], y - A[1]); return d < 0 ? 0 : clamp(1 - d / (band * clamp(r / 500, .4, 2))) * .9; } });
    ctx.restore();
  }

  // ---------- rotated code text on a receding wall ----------
  // Draws line n up a facade at X, from Z0..Z0+fw, reading bottom to top. Chunks get their own affine so the
  // glyph slant follows the perspective. colors: {text, red}
  // Glyph "up" points along -Z on the left wall and +Z on the right, so both walls read bottom-to-top, unmirrored.
  function wallLine(ctx, C, X, Zc, gs, n, col, y0 = -1.5, maxY = -1e9) {
    const adv = gs * .6, up = X < 0 ? -1 : 1, zb = Zc - up * gs * .36, k = gs / 100, e = .05;
    let off = 0;
    ctx.save(); ctx.font = '700 100px "JetBrains Mono"';
    for (const [s, kind] of segs(n)) {
      ctx.fillStyle = kind === 'red' ? col.red : col.text;
      for (let j = 0; j < s.length; j += 6) {
        const chunk = s.slice(j, j + 6), Y = y0 - (off + j) * adv; if (Y < maxY) break; if (!chunk.trim()) continue;
        const O = pj(C, X, Y, zb); if (O[2] < 2) continue;
        const Ua = pj(C, X, Y - e, zb), Va = pj(C, X, Y, zb + up * e);
        ctx.setTransform((Ua[0] - O[0]) / e * k, (Ua[1] - O[1]) / e * k, -(Va[0] - O[0]) / e * k, -(Va[1] - O[1]) / e * k, O[0], O[1]); ctx.fillText(chunk, 0, 0);
      }
      off += s.length;
    }
    ctx.restore();
  }
  const lenOf = n => code(n).length;

  // ---------- SHOT 1 (87.74-91.10): the canyon of code ----------
  const CAN = { sp: 6, fw: 5.2, WL: -26, WR: 30, gs: 3.2, first: 8960, last: 9090 };
  const zOf = n => (n - 9000) * CAN.sp;                                  // near edge of tower n (both walls)
  const towerH = n => (lenOf(n) + 6) * CAN.gs * .6 + 10 + hash(n * 5.1) * 30;
  const PLANTS = [87.74, 88.236, 88.631, 89.072, W12.now];
  function canyonCam(t) {
    const k = PLANTS.filter(p => p - 1 / 24 <= t).length - 1, i = clamp(k, 0, 4);
    const p0 = PLANTS[i], p1 = PLANTS[Math.min(4, i + 1)], f = i >= 4 ? 0 : clamp((t - p0) / (p1 - p0));
    const zr = zOf(9008 + i) + CAN.fw / 2 - 5 + (i >= 4 ? 0 : easeInOut(f) * CAN.sp);
    return { i, f, zr };
  }
  function canyonScene(c, C, t, lit, litSign, face) {
    const ink0 = lit ? P : K, txt0 = lit ? K : G2, red0 = lit ? R : RD;
    // sky, then the far exit slot of light and the floor
    fillPts(c, rect(-50, -50, W + 100, H + 100), P, false);
    const fl = [pj(C, CAN.WL, 0, C.z + 3), pj(C, CAN.WL, 0, C.z + 4000), pj(C, CAN.WR, 0, C.z + 4000), pj(C, CAN.WR, 0, C.z + 3)];
    fillPts(c, [[fl[0][0] - 3000, fl[0][1] + 2000], [fl[1][0], fl[1][1]], [fl[2][0], fl[2][1]], [fl[3][0] + 3000, fl[3][1] + 2000]], ink0, false);
    // floor seams: gutter lines toward the vanishing point and one cross line per code line
    c.save(); c.lineWidth = 3; c.strokeStyle = lit ? G2 : G1; c.beginPath();
    for (const X of [-18, -9, 0, 9, 18]) { const a = pj(C, X, 0, C.z + 6), b = pj(C, X, 0, C.z + 3000); c.moveTo(a[0], a[1]); c.lineTo(b[0], b[1]); }
    for (let n = CAN.first; n < CAN.last; n++) { const z = zOf(n); if (z < C.z + 4) continue; const a = pj(C, CAN.WL, 0, z), b = pj(C, CAN.WR, 0, z); c.moveTo(a[0], a[1]); c.lineTo(b[0], b[1]); }
    c.stroke(); c.restore();
    // towers, far to near, both walls
    for (let n = CAN.last; n >= CAN.first; n--) for (const X of [CAN.WL, CAN.WR]) {
      const z0 = zOf(n) + (X > 0 ? 2.1 : 0), z1 = z0 + CAN.fw; if (z1 < C.z + 3) continue;
      const hN = X > 0 ? towerH(n + 400) : towerH(n), za = Math.max(z0, C.z + 3);
      const q = [pj(C, X, 0, za), pj(C, X, 0, z1), pj(C, X, -hN, z1), pj(C, X, -hN, za)];
      if (Math.max(q[0][0], q[1][0]) < -40 || Math.min(q[0][0], q[1][0]) > W + 40) continue;
      // the tower's near side face (depth into the wall), so the skyline reads as separate slabs
      const d = X < 0 ? -6 : 6, s0 = [pj(C, X, 0, za), pj(C, X + d, 0, za), pj(C, X + d, -hN, za), pj(C, X, -hN, za)];
      if (za === z0) fillPts(c, s0.map(p => [p[0], p[1]]), lit ? G3 : mix(K, P, .08), false);
      fillPts(c, q.map(p => [p[0], p[1]]), ink0, false);
      const on = n === face && X < 0;
      if (C.f / ((z0 + z1) / 2 - C.z) * CAN.gs > 3) wallLine(c, C, X, (z0 + z1) / 2, CAN.gs, X > 0 ? n + 400 : n, { text: on && lit ? K : txt0, red: red0 }, -1.8, -hN + 2);
      // roof line
      c.strokeStyle = lit ? K : G1; c.lineWidth = 2; c.beginPath(); c.moveTo(q[2][0], q[2][1]); c.lineTo(q[3][0], q[3][1]); c.stroke();
    }
    // blade signs: the gutter, one number per line, facing the camera
    for (let n = 9030; n >= 8990; n--) {
      const z = zOf(n) + CAN.fw * .5; if (z < C.z + 4) continue;
      const a = pj(C, CAN.WL, -19, z), b = pj(C, CAN.WL + 3.8, -5, z), w = b[0] - a[0], h = b[1] - a[1]; if (b[0] < -10 || a[0] > W) continue;
      const on = n === litSign, fillS = on ? (lit ? WH : P) : (lit ? P : K), tc = on ? K : (lit ? K : G2);
      fillPts(c, [pj(C, CAN.WL, -17, z), pj(C, CAN.WL + 1.2, -17, z), pj(C, CAN.WL + 1.2, -16.4, z), pj(C, CAN.WL, -16.4, z)].map(p => [p[0], p[1]]), lit ? K : G1, false);
      c.save(); c.setTransform(1, 0, 0, 1, 0, 0);
      fillPts(c, rect(a[0], a[1], w, h), fillS, false);
      c.strokeStyle = on || lit ? K : G2; c.lineWidth = Math.max(1.5, w * .06); c.strokeRect(a[0] + w * .1, a[1] + w * .1, w * .8, h - w * .2);
      const ds = String(n); for (let j = 0; j < 4; j++) txt(c, ds[j], a[0] + w / 2, a[1] + h * (.24 + j * .205), { font: 'mono', weight: 800, size: w * .78, color: n === 9012 && on ? R : tc, align: 'center', base: 'middle' });
      c.restore();
    }
  }
  function canyon(ctx, t, lt, dur) {
    const tc = twos(t), { i, f, zr } = canyonCam(tc), zs = canyonCam(t).zr;
    const stopK = seg(t, W12.now + .1, 91.1), push = easeInOut(stopK);
    const C = { x: lerp(4, -2, push), y: -21 + push * 3, z: zs - lerp(50, 38, seg(t, 87.74, 91.1)), f: 1100, cx: 960 + drift(t, 5)[0], cy: 360 + drift(t, 5)[1] };
    const litSign = 9008 + i, face = t >= W12.now + .12 ? 9012 : -1;
    canyonScene(ctx, C, t, false, litSign, face);
    // the rabbit: steps planted on the plant times (twos), head turns to the 9012 tower after 'now'
    const X = -13.5, gp = pj(C, X, 0, zr), s = C.f / gp[2];
    const step = i >= 4 ? 0 : Math.sin(f * Math.PI), side = i % 2;
    const look = kf(tc, [[W12.now + .1, 0], [W12.now + .45, -.9]]);
    const lift = i >= 4 ? [0, 0] : side ? [step, 0] : [0, step];
    const stopHit = hit(t, [W12.now], 10);
    // where the beam points: the lit sign ahead, then it swings onto the 9012 tower face
    const zsg = zOf(litSign) + CAN.fw * .5, sign = pj(C, CAN.WL + 1.9, -12, zsg), tower = pj(C, CAN.WL, -26, zOf(9012) + CAN.fw * .5);
    const sw = easeInOut(seg(t, W12.now + .12, W12.now + .6)), T = [lerp(sign[0], tower[0], sw), lerp(sign[1], tower[1], sw)];
    const A0 = [gp[0] + (2.2 + look * .4) * s, gp[1] - (4.7 + step * .25) * s];
    light(ctx, A0, T, lerp(.13, .16, sw), c => canyonScene(c, C, t, true, litSign, face));
    bunnyBack(ctx, gp[0], gp[1], s, { lift, bob: step * .25 - stopHit * .2, look, sway: i >= 4 ? stopHit * .6 : Math.sin((i + f) * Math.PI) * .6, earA: stopHit * 6 });
  }

  // ---------- placeholders for the rest (built below) ----------
  function todo(label) { return (ctx, t) => { fillPts(ctx, rect(0, 0, W, H), K, false); txt(ctx, label + ' ' + t.toFixed(2), W / 2, H / 2, { size: 80, align: 'center', base: 'middle', color: P }); }; }

  chapter('bridge', 87.74, 104.63, [[87.74, canyon], [91.10, todo('beam')], [cutAt(W12.there), todo('eye')], [94.40, todo('paw')], [cutAt(W12.caps), todo('flip')],
    [97.60, todo('merge')], [cutAt(W12.shipped), todo('ship')], [101.10, todo('flaw')]]);
})();
