// Bake the song data into src/data.js so studio.html works from file:// without fetch.
//   node tools/build_data.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const ly = JSON.parse(readFileSync('assets/lyrics_timed.json', 'utf8'));
const dr = JSON.parse(readFileSync('assets/drums.json', 'utf8'));
const lines = ly.lines.map(l => ({ sec: l.section, text: l.text, a: l.start, b: l.end, hold: l.hold || null,
  words: l.words.map(w => ({ w: w.w, a: w.start, b: w.end })) }));
writeFileSync('src/data.js', `// Generated by tools/build_data.mjs from assets/lyrics_timed.json and assets/drums.json. Do not edit.
const LINES = ${JSON.stringify(lines)};
// Beat grid snapped to the drum attacks; kicks fall on odd beat indices, snares on even ones (only where the drums play).
const BEATS = ${JSON.stringify(dr.beats)};
const KICKS = ${JSON.stringify(dr.kicks)};
const SNARES = ${JSON.stringify(dr.snares)};
`);
console.log(`src/data.js: ${lines.length} lines, ${dr.beats.length} beats, ${dr.kicks.length} kicks, ${dr.snares.length} snares`);
