# The lyrics as sung: (section, text for the aligner, display text). Display text must have the same word count.
CH1 = [
    ('This could have been a text', 'This could have been a text'),
    ("Could've hit send, could've done it in a sec", "Could've hit send, could've done it in a sec"),
    ("Could've dropped it in Teams", "Could've dropped it in Teams"),
    ("Could've slid into Slack", "Could've slid into Slack"),
]
LINES = [
    ('verse1', 'Hey, you got a sec?', '"Hey, you got a sec?"'),
    ('verse1', "Yeah, that's never just a sec", "Yeah, that's never just a sec"),
    ('verse1', 'Nothing urgent, just a quick sync', '"Nothing urgent, just a quick sync"'),
    ('verse1', 'There goes half my day, I think', 'There goes half my day, I think'),
    ('verse1', 'Calendar block, little blue box', 'Calendar block, little blue box'),
    ('verse1', 'Fifteen minutes, but everybody talks', '"Fifteen minutes," but everybody talks'),
    ('verse1', "You could've typed it, crystal clear", "You could've typed it, crystal clear"),
    ('verse1', 'But somehow I gotta hear it in your ear', 'But somehow I gotta hear it in your ear'),
    ('pre1', "You said, let's just hop on", 'You said, "let\'s just hop on"'),
    ('pre1', 'Like that solves everything', 'Like that solves everything'),
    ('pre1', "You said, it'll be quick", 'You said, "it\'ll be quick"'),
    ('pre1', "That's the funniest thing", "That's the funniest thing"),
    *[('chorus1', a, b) for a, b in CH1],
    ('chorus1', "Now I'm staring at your camera while you circle back", "Now I'm staring at your camera while you circle back"),
    ('chorus1', 'This could have been an email', 'This could have been an email'),
    ('chorus1', "Two little lines and we're done for real", "Two little lines and we're done for real"),
    ('chorus1', 'But you needed my face for a question with no depth', 'But you needed my face for a question with no depth'),
    ('chorus1', 'God, this could have been a text', 'God, this could have been a text'),
    ('tag1', 'Oh, oh, oh, oh, oh', 'Oh, oh, oh, oh, oh'),
    ('tag1', 'This could have been a text', 'This could have been a text'),
    ('tag1', 'Oh, oh, oh, oh, oh', 'Oh, oh, oh, oh, oh'),
    ('verse2', 'Just wanted your thoughts on this', '"Just wanted your thoughts on this"'),
    ('verse2', 'You want a meeting for a sentence?', 'You want a meeting for a sentence?'),
    ('verse2', 'Can we talk through what happened here?', '"Can we talk through what happened here?"'),
    ('verse2', 'Sure, give me thirty minutes to disappear', 'Sure, give me thirty minutes to disappear'),
    ('verse2', 'Screen share, can you see my screen?', 'Screen share, "can you see my screen?"'),
    ('verse2', "Yeah, I've got the same one on my screen", "Yeah, I've got the same one on my screen"),
    ('verse2', 'Then you ask what I would suggest', 'Then you ask what I would suggest'),
    ('verse2', 'Buddy, you literally wrote the context in the deck', 'Buddy, you literally wrote the context in the deck'),
    ('pre2', "You said, let's just jump on", 'You said, "let\'s just jump on"'),
    ('pre2', "Like we're defusing a bomb", "Like we're defusing a bomb"),
    ('pre2', 'You said, just a quick one', 'You said, "just a quick one"'),
    ('pre2', 'And the quick one lasted an hour long', 'And the quick one lasted an hour long'),
    *[('chorus2', a, b) for a, b in CH1],
    ('chorus2', "Now I'm nodding at my laptop while you're talking in abstracts", "Now I'm nodding at my laptop while you're talking in abstracts"),
    ('chorus2', 'This could have been an email', 'This could have been an email'),
    ('chorus2', 'One clean paragraph, nobody has to bail', 'One clean paragraph, nobody has to bail'),
    ('chorus2', 'But you needed a call for a question with no depth', 'But you needed a call for a question with no depth'),
    ('chorus2', 'God, this could have been a text', 'God, this could have been a text'),
    ('post', 'Oh, oh, oh, oh, another meeting', 'Oh, oh, oh, oh, another meeting'),
    ('post', 'Oh, oh, oh, oh, another link', 'Oh, oh, oh, oh, another link'),
    ('post', 'Oh, oh, oh, oh, another you free?', 'Oh, oh, oh, oh, another "you free?"'),
    ('post', 'Oh, oh, oh, oh, give me a break', 'Oh, oh, oh, oh, give me a break'),
    ('verse3', "Then there's the follow-up after the call", "Then there's the follow-up after the call"),
    ('verse3', 'Just recapping, and you write it all', '"Just recapping," and you write it all'),
    ('verse3', "So now we've got the minutes, notes and thread", "So now we've got the minutes, notes and thread"),
    ('verse3', "For something you could've typed from the start instead", "For something you could've typed from the start instead"),
    ('verse3', "And I'm learning things I never knew", "And I'm learning things I never knew"),
    ('verse3', 'Like apparently noted needs a Zoom', 'Like apparently "noted" needs a Zoom'),
    ('verse3', 'You sent a deck, I read the deck', 'You sent a deck, I read the deck'),
    ('verse3', 'Then booked a call to explain the deck', 'Then booked a call to explain the deck'),
    ('bridge', 'If it needs emotion, call me', 'If it needs emotion, call me'),
    ('bridge', "If the building's on fire, call me", "If the building's on fire, call me"),
    ('bridge', "If we're changing half the company", "If we're changing half the company"),
    ('bridge', 'Yeah, okay, call me', 'Yeah, okay, call me'),
    ('bridge', 'But hey, can you approve this?', 'But "hey, can you approve this?"'),
    ('bridge', 'Type it', 'Type it.'),
    ('bridge', 'Can you send that over?', '"Can you send that over?"'),
    ('bridge', 'Type it', 'Type it.'),
    ('bridge', 'Any update on this?', '"Any update on this?"'),
    ('bridge', 'Type it', 'Type it.'),
    ('bridge', 'Why am I looking at your forehead?', 'Why am I looking at your forehead?!'),
    ('breakdown', 'Send the message', 'SEND. THE. MESSAGE.'),
    ('breakdown', 'Send the message', 'SEND. THE. MESSAGE.'),
    ('breakdown', 'You have a keyboard', 'You have a keyboard.'),
    ('breakdown', 'You have my address', 'You have my address.'),
    ('breakdown', 'You have Slack', 'You have Slack.'),
    ('breakdown', 'You have Teams', 'You have Teams.'),
    ('breakdown', 'You have email', 'You have email.'),
    ('breakdown', 'What are we doing?', 'WHAT ARE WE DOING?'),
    ('final', 'This could have been a text', 'This could have been a text'),
    ('final', "Could've hit send, could've done it in a sec", "Could've hit send, could've done it in a sec"),
    ('final', "Could've dropped it in Teams", "Could've dropped it in Teams"),
    ('final', "Could've kept the whole thing clean", "Could've kept the whole thing clean"),
    ('final', "Now I'm trapped inside a meeting", "Now I'm trapped inside a meeting"),
    ('final', "That should've never been", "That should've never been"),
    ('final', 'This could have been an email', 'This could have been an email'),
    ('final', 'Nobody needed your voice to tell the tale', 'Nobody needed your voice to tell the tale'),
    ('final', 'But you booked a call for a thought with no context', 'But you booked a call for a thought with no context'),
    ('final', "And everybody's thinking", "And everybody's thinking:"),
    ('final_tag', 'This could have been a message', 'This could have been a message'),
    ('final_tag', 'This could have been a text', 'This could have been a text'),
    ('final_tag', 'This could have been a text', 'This could have been a text'),
    ('final_tag', 'This could have been a text', 'THIS COULD HAVE BEEN A TEXT'),
    ('final_tag', 'This could have been a text', 'This could have been a text'),
    ('outro', 'Hey, got a minute?', '"Hey, got a minute?"'),
    ('outro', 'No.', 'No.'),
    ('outro', 'Send me the damn text.', 'Send me the damn text.'),
]
