// Bake the song data into src/data.js so studio.html works from file:// without fetch.
//   node tools/build_data.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const ly = JSON.parse(readFileSync('assets/lyrics_timed.json', 'utf8'));
const beats = JSON.parse(readFileSync('assets/beats.json', 'utf8')).beats;
const lines = ly.lines.map(l => ({ sec: l.section, text: l.text, a: l.start, b: l.end, hold: l.hold || null,
  words: l.words.map(w => ({ w: w.w, a: w.start, b: w.end })) }));
writeFileSync('src/data.js', `// Generated by tools/build_data.mjs from assets/lyrics_timed.json and assets/beats.json. Do not edit.
const LINES = ${JSON.stringify(lines)};
const BEATS = ${JSON.stringify(beats)};
`);
console.log(`src/data.js: ${lines.length} lines, ${beats.length} beats`);
